//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apiario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apiario
    {
        public Apiario()
        {
            this.Caixa = new HashSet<Caixa>();
            this.DadosApiario = new HashSet<DadosApiario>();
        }
    
        public int idApiario { get; set; }
        public int idCliente { get; set; }
        public string localizacao { get; set; }
        public int quantasVezes { get; set; }
        public System.TimeSpan hora { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<Caixa> Caixa { get; set; }
        public virtual ICollection<DadosApiario> DadosApiario { get; set; }
    }
}
