//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apiario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caixa
    {
        public Caixa()
        {
            this.DadosCaixa = new HashSet<DadosCaixa>();
        }
    
        public int idCaixa { get; set; }
        public int idApiario { get; set; }
        public string situacao { get; set; }
        public bool conexao { get; set; }
    
        public virtual Apiario Apiario { get; set; }
        public virtual ICollection<DadosCaixa> DadosCaixa { get; set; }
    }
}
