//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apiario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DadosCaixa
    {
        public int idDadosCaixa { get; set; }
        public int idCaixa { get; set; }
        public double peso { get; set; }
        public double fluxoAbelhas { get; set; }
        public System.DateTime dataDadosCaixa { get; set; }
    
        public virtual Caixa Caixa { get; set; }
    }
}
