//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apiario.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApiarioEntities1 : DbContext
    {
        public ApiarioEntities1()
            : base("name=ApiarioEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrador> Administrador { get; set; }
        public virtual DbSet<Apiario> Apiario { get; set; }
        public virtual DbSet<Atendimento> Atendimento { get; set; }
        public virtual DbSet<Caixa> Caixa { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<DadosApiario> DadosApiario { get; set; }
        public virtual DbSet<DadosCaixa> DadosCaixa { get; set; }
    }
}
